<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

/** @var string $identifier */
$identifier = 'SOME_IDENTIFIER_KEY';

/** @var \Zend\Config\Config $poll */
$poll = $this->poll()->find($identifier);

?>
<h1>
    <?= $poll->get('subject'); ?>
    <small><?= $poll->get('total'); ?></small>
</h1>

<form action="#" method="post">
    <ul>
        <?php foreach ($poll->get('options') as $key => $option): ?>
            <li>
                <?= $this->formRadio($this->poll()->optionElement($option)); ?>
                <b><?= $option->get('percent'); ?></b>
            </li>
        <?php endforeach; ?>
    </ul>

    <?= $this->formElement($this->poll()->identifierElement()); ?>
    <button type="submit">Submit</button>
</form>