<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Voting\Controller;

use Zend\Mvc\Controller\AbstractActionController;

/**
 * Class IndexController
 * @package MSBios\Voting\Controller
 */
class IndexController extends AbstractActionController
{
    /**
     * @return \Zend\View\Model\ViewModel
     */
    public function indexAction()
    {

        if ($this->getRequest()->isPost()) {
            $this->poll()->setValue($this->params()->fromPost());
        }

        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}
